# Generated by Django 4.0.6 on 2022-07-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=1000)),
                ('ProductBrand', models.CharField(max_length=100)),
                ('ProductWeb', models.CharField(max_length=100))
            ],
        ),
    ]
