# Generated by Django 4.0.6 on 2022-07-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0004_rename_productweb_products_productweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductWeb',
            field=models.CharField(default='Shopee', max_length=100),
        ),
    ]
